# Generated by Django 5.1.1 on 2024-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (2, 'Deactivate'), (3, 'Delete')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (2, 'Deactivate'), (3, 'Delete')], default=1, max_length=50),
        ),
    ]
